schema:
  - http://graphql.lvh.me:3001:
      headers:
        Authorization: Bearer faeb9172e232a75339242faafb9e56de8c8f13b735f7090964
        X-Exclude-Invalid: true
documents: './graphql/**/*.graphql'
generates:
  graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations:
          scalars:
            IntType: number
            FloatType: number
            BooleanType: boolean
            CustomData: Record<string, unknown>
            DateTime: string
            Date: string
            JsonField: Record<string, unknown>
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node
